<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="HandheldFriendly" content="true">

<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
<script src="/assets/js/jquery-1.12.4.min.js" ></script>
<script src="/assets/js/bootstrap.min.js"></script>
    <title>webd-torr Client</title>
  </head>
  <body>
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">webd-torr Client</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/myTorrents/">Torrents</a></li>
        <li><a href="/newContent/">New Content</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/settings/">Settings</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
  {{mainContent}}
</div>
  </body>
</html>